In [1]:
import numpy as np  

Numpy Array Declaration 

In [2]:
a = np.array([1, 2, 3, 4, 5]) 

In [3]:
print(a, type(a)) 

[1 2 3 4 5] <class 'numpy.ndarray'>


In [4]:
b = np.array([[1, 2], [3, 4]])

In [5]:
print(b, type(b)) 

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [6]:
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) 

In [7]:
print(c, type(c)) 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] <class 'numpy.ndarray'>


In [8]:
# list comprehension 

In [9]:
np.array([item  for item in range(1, 101)])

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [10]:
np.array([0.00 for i in range(25)]).reshape(5, 5) 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.zeros((5, 5)) 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((2,2)) 

array([[1., 1.],
       [1., 1.]])

In [13]:
np.array([1.0 for i in range(4)]).reshape(2, 2)

array([[1., 1.],
       [1., 1.]])

In [14]:
np.empty((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.full(shape = (5, 4),fill_value = 15)  

array([[15, 15, 15, 15],
       [15, 15, 15, 15],
       [15, 15, 15, 15],
       [15, 15, 15, 15],
       [15, 15, 15, 15]])

In [16]:
np.eye(3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
[i for i in range(1, 11, 1)]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [18]:
np.arange(11) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
np.linspace(0, 5, 5)  

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [20]:
np.array([item for item in range(90)]).reshape(2, 5, 3, 3)

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]],

        [[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]]],


       [[[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]],

        [[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]],

        [[81, 82, 83],
         [84, 85, 86],
         [87, 88, 89]]]])

In [21]:
a = np.arange(1, 11, 1) 

print(a) 

[ 1  2  3  4  5  6  7  8  9 10]


In [22]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(a) 
print(b)  

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [23]:
np.add(a, b) 

array([[ 6,  8],
       [10, 12]])

In [24]:
a + b 

array([[ 6,  8],
       [10, 12]])

In [25]:
np.subtract(b, a) 

array([[4, 4],
       [4, 4]])

In [26]:
b - a 

array([[4, 4],
       [4, 4]])

In [27]:
a * b 

array([[ 5, 12],
       [21, 32]])

In [28]:
np.multiply(a, b) 

array([[ 5, 12],
       [21, 32]])

In [29]:
np.divide(a, b) 

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [30]:
a / b 

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [31]:
np.dot(a, b) 

array([[19, 22],
       [43, 50]])

In [32]:
ar = np.array([[1, 4], [9, 16]])

print(ar) 

[[ 1  4]
 [ 9 16]]


In [33]:
np.sqrt(ar) 

array([[1., 2.],
       [3., 4.]])

In [34]:
arr = np.array([[1, 1], [2, 2, ]])

np.exp(arr) 

array([[2.71828183, 2.71828183],
       [7.3890561 , 7.3890561 ]])

In [35]:
np.sin(arr) 

array([[0.84147098, 0.84147098],
       [0.90929743, 0.90929743]])

In [36]:
np.cos(arr) 

array([[ 0.54030231,  0.54030231],
       [-0.41614684, -0.41614684]])

In [37]:
print(a) 
print(b) 

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [38]:
print(a > b) 

[[False False]
 [False False]]


In [39]:
print(a > 2) 

[[False False]
 [ True  True]]


In [40]:
# Aggregate Operations 

print(a) 
print(f"Sum = {np.sum(a)}")
print(f"Max = {np.max(a)}")
print(f"Min = {np.min(a)}")
print(f"Row Wise Sum = {np.sum(a,  axis = 1)}")
print(f"Column Wise Sum = {np.sum(a, axis = 0)}")
print(f"Row Wise Max = {np.max(a, axis = 1)}")
print(f"Column Wise Max = {np.max(a, axis = 0)}")

[[1 2]
 [3 4]]
Sum = 10
Max = 4
Min = 1
Row Wise Sum = [3 7]
Column Wise Sum = [4 6]
Row Wise Max = [2 4]
Column Wise Max = [3 4]


In [41]:
print(a) 

[[1 2]
 [3 4]]


In [42]:
np.mean(a) 

np.float64(2.5)

In [43]:
np.median(a) 

np.float64(2.5)

In [44]:
a = [[1, 2], [3, 4]] 

In [45]:
print(a) 

[[1, 2], [3, 4]]


In [46]:
new = a.copy() 
print(new) 

[[1, 2], [3, 4]]


In [47]:
new2 = np.copy(a) 
print(new2)

[[1 2]
 [3 4]]


In [48]:
# Sorting 

arr = np.random.randint(1, 20, 12).reshape(3, 4) 

print(arr, end = '\n\n') 

arr.sort(axis = 0) 

print(arr) 

[[ 8 14  8  1]
 [14  7  7 16]
 [17 16 10 13]]

[[ 8  7  7  1]
 [14 14  8 13]
 [17 16 10 16]]


In [49]:
# Sorting 

arr = np.random.randint(1, 20, 12).reshape(3, 4) 

print(arr, end = '\n\n') 

arr.sort(axis = 1) 

print(arr) 

[[19 18 13 18]
 [11 10  2  1]
 [17  3 19 14]]

[[13 18 18 19]
 [ 1  2 10 11]
 [ 3 14 17 19]]


In [50]:
arr.sort(axis = 0)  

In [51]:
arr = np.random.randint(1, 100, 20).reshape(4, 5) 

In [52]:
print(arr) 

[[40  1 25 80 64]
 [81 46 25 31 79]
 [80 98 26 85 62]
 [57 25 22  3 46]]


In [53]:
len(arr) 

4

In [54]:
arr[0] 

array([40,  1, 25, 80, 64], dtype=int32)

In [55]:
len(arr[0]) 

5

In [56]:
print(f"Matrix\n{arr}\nNo of Rows : {len(arr)}\nNo of Columns : {len(arr[0])}")

Matrix
[[40  1 25 80 64]
 [81 46 25 31 79]
 [80 98 26 85 62]
 [57 25 22  3 46]]
No of Rows : 4
No of Columns : 5


In [57]:
arr[2, 2]

np.int32(26)

In [58]:
arr[3, 3] 

np.int32(3)

In [59]:
print(arr) 

[[40  1 25 80 64]
 [81 46 25 31 79]
 [80 98 26 85 62]
 [57 25 22  3 46]]


In [60]:
arr[:2, :]

array([[40,  1, 25, 80, 64],
       [81, 46, 25, 31, 79]], dtype=int32)

In [61]:
arr[2:, 3:]

array([[85, 62],
       [ 3, 46]], dtype=int32)

In [62]:
arr[1:3, 1:4]

array([[46, 25, 31],
       [98, 26, 85]], dtype=int32)

In [63]:
new = np.random.randint(1, 100, 25).reshape(5, 5) 

In [64]:
new

array([[48, 24, 83, 87, 86],
       [15, 28,  4, 73, 46],
       [ 1, 28, 40, 18, 13],
       [16,  3, 16, 16, 45],
       [18, 16, 60, 94, 30]], dtype=int32)

In [65]:
new[[0, 1, 2, 3, 4],[2, 3, 2, 1, 2]]

array([83, 73, 40,  3, 60], dtype=int32)

In [66]:
new[1:4, 1:4]

array([[28,  4, 73],
       [28, 40, 18],
       [ 3, 16, 16]], dtype=int32)

In [70]:
a = np.random.randint(10, 100, 10).reshape(2, 5) 

In [71]:
print(a) 

[[92 52 79 45 13]
 [63 67 36 99 70]]


In [72]:
a.T

array([[92, 63],
       [52, 67],
       [79, 36],
       [45, 99],
       [13, 70]], dtype=int32)

In [73]:
# Changing shape 

In [74]:
a = np.random.randint(1, 100, 30).reshape(3, 10) 


In [75]:
a

array([[58, 31, 45,  3, 73, 47, 67, 77,  2, 12],
       [23, 26, 19, 89, 46, 34, 90, 19, 74,  8],
       [44, 61, 70, 82, 67, 16,  4,  9, 90, 64]], dtype=int32)

In [76]:
d_1 = a.ravel() 

In [77]:
d_1

array([58, 31, 45,  3, 73, 47, 67, 77,  2, 12, 23, 26, 19, 89, 46, 34, 90,
       19, 74,  8, 44, 61, 70, 82, 67, 16,  4,  9, 90, 64], dtype=int32)

In [78]:
a = np.array([[[1, 2], [3, 4]], [[5, 6],[7,8]]])

In [79]:
a.shape

(2, 2, 2)

In [80]:
print(a) 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [81]:
a.ravel() 

array([1, 2, 3, 4, 5, 6, 7, 8])

In [82]:
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [83]:
four_dimensional_array = np.random.randint(1, 100, 16).reshape(2, 2, 2, 2) 

In [84]:
four_dimensional_array

array([[[[53, 33],
         [14, 13]],

        [[42, 66],
         [22, 11]]],


       [[[ 3, 99],
         [ 8, 12]],

        [[ 4, 77],
         [23, 91]]]], dtype=int32)

In [88]:
arr = np.random.randint(1, 100, 256).reshape(2, 2,  2, 2, 2, 2, 2, 2) 

In [89]:
arr

array([[[[[[[[79, 11],
             [ 5, 18]],

            [[98, 47],
             [23, 43]]],


           [[[79, 15],
             [94, 14]],

            [[72, 32],
             [40, 20]]]],



          [[[[45, 53],
             [ 4, 17]],

            [[26, 83],
             [ 6, 36]]],


           [[[98, 49],
             [ 6,  9]],

            [[42, 54],
             [82, 25]]]]],




         [[[[[28, 19],
             [56, 75]],

            [[11, 12],
             [56, 73]]],


           [[[60, 79],
             [82, 24]],

            [[53, 24],
             [54, 25]]]],



          [[[[95, 17],
             [ 9, 77]],

            [[37, 65],
             [66,  6]]],


           [[[22,  7],
             [28, 44]],

            [[27, 81],
             [69,  5]]]]]],





        [[[[[[13, 55],
             [52, 13]],

            [[64, 49],
             [68, 42]]],


           [[[86, 25],
             [ 5, 80]],

            [[64,  1],
             [17, 20]]]],



    

In [90]:
arr.ndim

8

In [92]:
np.random.randint(1, 100, 60).reshape(20, 3) 

array([[33, 36, 71],
       [54, 52, 21],
       [95, 96, 34],
       [ 4, 15, 97],
       [36, 24, 69],
       [13, 53, 45],
       [90, 62, 32],
       [93, 49, 94],
       [65, 28, 62],
       [87, 10,  7],
       [55, 62, 61],
       [59, 72, 20],
       [16, 73, 13],
       [62, 26, 78],
       [36, 56, 43],
       [69, 45, 83],
       [77, 83,  9],
       [49, 89, 13],
       [55, 54, 33],
       [10, 74, 99]], dtype=int32)

In [93]:
a = np.array([[1, 2], [3, 4]]) 
b = np.array([[5, 6], [7, 8]])

print(a) 
print(b) 

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [97]:
np.append(a, b) 

array([1, 2, 3, 4, 5, 6, 7, 8])

In [98]:
np.append(a, b, axis = 0) 

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [99]:
np.append(a, b, axis = 1) 

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [100]:
np.insert(a, 1, 5) 

array([1, 5, 2, 3, 4])

In [101]:
print(a) 

[[1 2]
 [3 4]]


In [102]:
np.insert(a, 0, 10) 

array([10,  1,  2,  3,  4])

In [103]:
np.delete(a, [1])

array([1, 3, 4])

In [104]:
print(a) 

[[1 2]
 [3 4]]


In [108]:
np.delete(a, [0]) 

array([2, 3, 4])

In [107]:
np.ravel(a) 

array([1, 2, 3, 4])

In [109]:
a

array([[1, 2],
       [3, 4]])

In [110]:
np.delete(a, [1, 2])

array([1, 4])

In [111]:
print(a) 

[[1 2]
 [3 4]]


In [112]:
a = np.random.randint(1, 100, 20).reshape(5, 4) 

In [113]:
a

array([[56, 56, 75, 14],
       [62, 91, 73, 72],
       [64, 60, 84,  7],
       [27, 83, 14, 61],
       [10, 80, 36, 97]], dtype=int32)

In [117]:
np.delete(a, [0, 1, 2, 3]).reshape(4, 4) 

array([[62, 91, 73, 72],
       [64, 60, 84,  7],
       [27, 83, 14, 61],
       [10, 80, 36, 97]], dtype=int32)