In [2]:
import numpy as np 
import pandas as pd 

import matplotlib.pyplot as plt 
import random 

In [3]:
a = np.array([1, 2, 3, 4, 5]) 
print(a, type(a)) 

[1 2 3 4 5] <class 'numpy.ndarray'>


In [4]:
a = np.array([item for item in range(1, 101)]).reshape(2, 2, 5, 5)   
print(a, a.shape) 

[[[[  1   2   3   4   5]
   [  6   7   8   9  10]
   [ 11  12  13  14  15]
   [ 16  17  18  19  20]
   [ 21  22  23  24  25]]

  [[ 26  27  28  29  30]
   [ 31  32  33  34  35]
   [ 36  37  38  39  40]
   [ 41  42  43  44  45]
   [ 46  47  48  49  50]]]


 [[[ 51  52  53  54  55]
   [ 56  57  58  59  60]
   [ 61  62  63  64  65]
   [ 66  67  68  69  70]
   [ 71  72  73  74  75]]

  [[ 76  77  78  79  80]
   [ 81  82  83  84  85]
   [ 86  87  88  89  90]
   [ 91  92  93  94  95]
   [ 96  97  98  99 100]]]] (2, 2, 5, 5)


In [5]:
alp = np.array([chr(i) for i in range(65, 91)]).reshape(13, 2) 
print(alp) 

[['A' 'B']
 ['C' 'D']
 ['E' 'F']
 ['G' 'H']
 ['I' 'J']
 ['K' 'L']
 ['M' 'N']
 ['O' 'P']
 ['Q' 'R']
 ['S' 'T']
 ['U' 'V']
 ['W' 'X']
 ['Y' 'Z']]


In [6]:
# 'A'.ord

In [7]:
ord('A')

65

In [8]:
ord('Z')

90

In [9]:
zero = np.zeros(shape = (5, 5)) 

In [10]:
def custom_zero(shape):
    summation = 1 
    for item in shape:
        summation *= item 
    return np.array([0.00 for i in range(summation)]).reshape(shape) 


In [11]:
new = custom_zero((5, 5)) 
print(new) 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
np.ones((3, 3)) 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:

np.empty(shape = (4, 4)) 

array([[4.67296746e-307, 1.69121096e-306, 1.29061074e-306,
        8.34441742e-308],
       [1.78022342e-306, 6.23058028e-307, 9.79107872e-307,
        6.89807188e-307],
       [7.56594375e-307, 6.23060065e-307, 1.78021527e-306,
        8.34454050e-308],
       [1.11261027e-306, 1.15706896e-306, 1.33512173e-306,
        5.87865998e+202]])

In [14]:
np.eye(5) 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.full(shape=(3, 3), fill_value=10) 

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [16]:
arr = np.arange(1, 101, 1)  
print(arr) 

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [17]:
li = [i for i in range(1, 101, 1)]
print(li) 

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]


In [18]:
arr = np.linspace(1, 10, 20) 
print(arr) 

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [19]:
arr = np.random.randint(1, 100, 25).reshape((5,5)) 
print(arr) 

[[84 93 24 74 83]
 [75 62 36  1 91]
 [67 16 73 54 18]
 [54 12 16  9 53]
 [90 25 45 51  2]]


In [20]:
arr[0, 0].dtype

dtype('int32')

In [21]:
# arr[0, 0].astype(np.int256)   

In [22]:
arr = np.array([item for item in range(1, 11, 1)])

In [23]:
arr.dtype

dtype('int64')

In [24]:
arr.astype(np.int32)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)

In [25]:
arr.dtype

dtype('int64')

In [26]:
arr.dtype

dtype('int64')

In [27]:
arr.astype(np.int32) 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)

In [28]:
arr.dtype

dtype('int64')

In [29]:
arr.dtype

dtype('int64')

In [30]:
arr[0].dtype

dtype('int64')

In [31]:
a = np.random.randint(1, 100, 100).reshape(10, 10) 
print(a.dtype) 
print(a[0, 0].dtype)

int32
int32


In [32]:
ar = np.array([1, 2, 3, 4, 5]) 
ar.dtype
ar[0].dtype

dtype('int64')

In [33]:
inspecting_array = np.random.randint(1, 1000, 150).reshape(10, 15) 
print(inspecting_array)

[[ 25 346 411 428 211 363 593 722 477  64 426 644 676 249 703]
 [926  44 592 439 757 701 167 245 344 939 529 489 881 442 908]
 [781 548 591 639 249 695 900  92 103 905  36  66 549 137 814]
 [447 685 132  61 935 278 417  54 204 526 849 630 524 886 808]
 [716 467 662 888  13 247 169 567 962 503 341 836 513 837 693]
 [197 273 626 574  23 310 104 641 361 513 496 613 821 514 222]
 [996 837 905 904 355 971 888 341 186 399 276 502 145 915 297]
 [992  95 597 957 515 219 830 418 702 761 710 118 801 444 208]
 [621 422 261 724 536 994 103 185 922 389 661 636 388 839 726]
 [704  53 698 295 636 123 147 221 457 631 704 224 776 961 964]]


In [34]:
print(f"Inspecting the Array : \nShape of Array : {inspecting_array.shape} --> Rows : {inspecting_array.shape[0]}, Columns : {inspecting_array.shape[1]}\nSize (Total No. of elements) : {inspecting_array.size}\nNumber of Dimensions : {inspecting_array.ndim}\nData Type of Each element : {inspecting_array.dtype}\nlength of array (No of rows) : {len(inspecting_array)}")

Inspecting the Array : 
Shape of Array : (10, 15) --> Rows : 10, Columns : 15
Size (Total No. of elements) : 150
Number of Dimensions : 2
Data Type of Each element : int32
length of array (No of rows) : 10


In [35]:
inspecting_array

array([[ 25, 346, 411, 428, 211, 363, 593, 722, 477,  64, 426, 644, 676,
        249, 703],
       [926,  44, 592, 439, 757, 701, 167, 245, 344, 939, 529, 489, 881,
        442, 908],
       [781, 548, 591, 639, 249, 695, 900,  92, 103, 905,  36,  66, 549,
        137, 814],
       [447, 685, 132,  61, 935, 278, 417,  54, 204, 526, 849, 630, 524,
        886, 808],
       [716, 467, 662, 888,  13, 247, 169, 567, 962, 503, 341, 836, 513,
        837, 693],
       [197, 273, 626, 574,  23, 310, 104, 641, 361, 513, 496, 613, 821,
        514, 222],
       [996, 837, 905, 904, 355, 971, 888, 341, 186, 399, 276, 502, 145,
        915, 297],
       [992,  95, 597, 957, 515, 219, 830, 418, 702, 761, 710, 118, 801,
        444, 208],
       [621, 422, 261, 724, 536, 994, 103, 185, 922, 389, 661, 636, 388,
        839, 726],
       [704,  53, 698, 295, 636, 123, 147, 221, 457, 631, 704, 224, 776,
        961, 964]], dtype=int32)

In [36]:
inspecting_array = inspecting_array.astype(float) 

In [37]:
inspecting_array

array([[ 25., 346., 411., 428., 211., 363., 593., 722., 477.,  64., 426.,
        644., 676., 249., 703.],
       [926.,  44., 592., 439., 757., 701., 167., 245., 344., 939., 529.,
        489., 881., 442., 908.],
       [781., 548., 591., 639., 249., 695., 900.,  92., 103., 905.,  36.,
         66., 549., 137., 814.],
       [447., 685., 132.,  61., 935., 278., 417.,  54., 204., 526., 849.,
        630., 524., 886., 808.],
       [716., 467., 662., 888.,  13., 247., 169., 567., 962., 503., 341.,
        836., 513., 837., 693.],
       [197., 273., 626., 574.,  23., 310., 104., 641., 361., 513., 496.,
        613., 821., 514., 222.],
       [996., 837., 905., 904., 355., 971., 888., 341., 186., 399., 276.,
        502., 145., 915., 297.],
       [992.,  95., 597., 957., 515., 219., 830., 418., 702., 761., 710.,
        118., 801., 444., 208.],
       [621., 422., 261., 724., 536., 994., 103., 185., 922., 389., 661.,
        636., 388., 839., 726.],
       [704.,  53., 698., 295., 636.,

In [38]:
# MatheMatical Operations 

# AritheMatic Operations 


a = np.random.randint(1, 10, 5) 
b = np.random.randint(1, 10, 5) 

print(f"a = {a}, b = {b}")

a = [3 7 6 5 7], b = [5 4 1 8 3]


In [39]:
np.add(a, b) 

array([ 8, 11,  7, 13, 10], dtype=int32)

In [40]:
a + b 

array([ 8, 11,  7, 13, 10], dtype=int32)

In [41]:
np.subtract(a, b) 

array([-2,  3,  5, -3,  4], dtype=int32)

In [42]:
a - b 

array([-2,  3,  5, -3,  4], dtype=int32)

In [43]:
np.multiply(a, b) 

array([15, 28,  6, 40, 21], dtype=int32)

In [44]:
a * b 

array([15, 28,  6, 40, 21], dtype=int32)

In [45]:
np.divide(a, b) 

array([0.6       , 1.75      , 6.        , 0.625     , 2.33333333])

In [46]:
a / b 

array([0.6       , 1.75      , 6.        , 0.625     , 2.33333333])

In [47]:
a // b 

array([0, 1, 6, 0, 2], dtype=int32)

In [48]:
np.exp(a) 

array([  20.08553692, 1096.63315843,  403.42879349,  148.4131591 ,
       1096.63315843])

In [49]:
np.exp(1) 

np.float64(2.718281828459045)

In [50]:
np.log(10) 

np.float64(2.302585092994046)

In [51]:
np.log10(10) 

np.float64(1.0)

In [52]:
np.log(a) 

array([1.09861229, 1.94591015, 1.79175947, 1.60943791, 1.94591015])

In [53]:
np.sqrt(a) 

array([1.73205081, 2.64575131, 2.44948974, 2.23606798, 2.64575131])

In [54]:
np.sqrt(np.array([item**2 for item in range(1, 11, 1)]))

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [55]:
np.sin(a) 

array([ 0.14112001,  0.6569866 , -0.2794155 , -0.95892427,  0.6569866 ])

In [56]:
np.cos(a) 

array([-0.9899925 ,  0.75390225,  0.96017029,  0.28366219,  0.75390225])

In [57]:
np.tan(a) 

array([-0.14254654,  0.87144798, -0.29100619, -3.38051501,  0.87144798])

In [58]:
a = np.random.randint(1, 10, 9).reshape(3, 3) 
b = np.random.randint(1, 10, 9).reshape(3, 3)

print(f"a = {a}")
print(f"b = {b}")

print(np.dot(a, b)) 

a = [[1 4 3]
 [6 2 9]
 [3 7 2]]
b = [[3 2 4]
 [4 7 4]
 [5 4 3]]
[[34 42 29]
 [71 62 59]
 [47 63 46]]


In [59]:
a

array([[1, 4, 3],
       [6, 2, 9],
       [3, 7, 2]], dtype=int32)

In [60]:
b

array([[3, 2, 4],
       [4, 7, 4],
       [5, 4, 3]], dtype=int32)

In [61]:
b.T

array([[3, 4, 5],
       [2, 7, 4],
       [4, 4, 3]], dtype=int32)

In [62]:
np.transpose(b) 

array([[3, 4, 5],
       [2, 7, 4],
       [4, 4, 3]], dtype=int32)

In [63]:
print(a) 
print(b) 

[[1 4 3]
 [6 2 9]
 [3 7 2]]
[[3 2 4]
 [4 7 4]
 [5 4 3]]


In [64]:
a == b

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [65]:
a != b 

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [66]:
a < b

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [67]:
a > b

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [68]:
a <= b 

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [69]:
a >= b 

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [ ]:
# Aggregate, Sorting, Copy, Slicing,Subbestting, Indexing, array manipulation      

In [79]:
a=np.random.randint(1,100,9).reshape((3,3)) 

In [80]:
print(a) 

[[22 21 35]
 [51  3 86]
 [53 92 22]]


In [81]:
np.min(a) 

np.int32(3)

In [82]:
np.max(a) 

np.int32(92)

In [83]:
np.sum(a) 

np.int64(385)

In [85]:
385/9

42.77777777777778

In [84]:
np.mean(a) 

np.float64(42.77777777777778)

In [86]:
a.size

9

In [87]:
print(a) 

[[22 21 35]
 [51  3 86]
 [53 92 22]]


In [88]:
a.min(axis=1) 

array([21,  3, 22], dtype=int32)

In [89]:
a.min(axis=0) 

array([22,  3, 22], dtype=int32)

In [90]:
a.mean(axis=0) 

array([42.        , 38.66666667, 47.66666667])

In [91]:
78/3

26.0

In [109]:
a=np.random.randint(1,100,36).reshape((6,6)) 

In [110]:
print(a) 

[[65 70 39 53 44 85]
 [98 91 84 11  1 59]
 [52  4 47 23 80 22]
 [99 37 11  6 85 61]
 [42  3 90 66  7 30]
 [40 47 23  2 31 56]]


In [116]:
np.concat((a[:, 0], a[[4, 3, 2, 1], [1, 2, 3, 4]] , a[:, -1], a[[4, 3, 2, 1], [4, 3, 2, 1]]))

array([65, 98, 52, 99, 42, 40,  3, 11, 23,  1, 85, 59, 22, 61, 30, 56,  7,
        6, 47, 91], dtype=int32)

In [117]:
# Array Manipulation 

In [118]:
# Transpose 
# Shape 
# Combining Array 
# Splitting Array 

In [119]:
print(a) 

[[65 70 39 53 44 85]
 [98 91 84 11  1 59]
 [52  4 47 23 80 22]
 [99 37 11  6 85 61]
 [42  3 90 66  7 30]
 [40 47 23  2 31 56]]


In [120]:
a.T

array([[65, 98, 52, 99, 42, 40],
       [70, 91,  4, 37,  3, 47],
       [39, 84, 47, 11, 90, 23],
       [53, 11, 23,  6, 66,  2],
       [44,  1, 80, 85,  7, 31],
       [85, 59, 22, 61, 30, 56]], dtype=int32)

In [121]:
np.transpose(a) 

array([[65, 98, 52, 99, 42, 40],
       [70, 91,  4, 37,  3, 47],
       [39, 84, 47, 11, 90, 23],
       [53, 11, 23,  6, 66,  2],
       [44,  1, 80, 85,  7, 31],
       [85, 59, 22, 61, 30, 56]], dtype=int32)

In [122]:
a = np.random.randint(1, 100, 9).reshape((3, 3)) 

In [123]:
print(a) 

[[41 38 72]
 [79 89 78]
 [37 54 61]]


In [124]:
a.T

array([[41, 79, 37],
       [38, 89, 54],
       [72, 78, 61]], dtype=int32)

In [125]:
a = np.random.randint(1, 100, 9).reshape((3, 3)) 
b = np.random.randint(1, 100, 9).reshape((3, 3)) 

In [126]:
print(a) 
print(b) 

[[18 49 22]
 [39 71 74]
 [44 12 84]]
[[90 68 79]
 [86 40  3]
 [79 68 66]]


In [127]:
np.concatenate((a, b ), axis = 1) 

array([[18, 49, 22, 90, 68, 79],
       [39, 71, 74, 86, 40,  3],
       [44, 12, 84, 79, 68, 66]], dtype=int32)

In [130]:
np.c_[a, b]

array([[18, 49, 22, 90, 68, 79],
       [39, 71, 74, 86, 40,  3],
       [44, 12, 84, 79, 68, 66]], dtype=int32)

In [128]:
np.concatenate((a, b ), axis = 0) 

array([[18, 49, 22],
       [39, 71, 74],
       [44, 12, 84],
       [90, 68, 79],
       [86, 40,  3],
       [79, 68, 66]], dtype=int32)

In [129]:
np.r_[a, b] 

array([[18, 49, 22],
       [39, 71, 74],
       [44, 12, 84],
       [90, 68, 79],
       [86, 40,  3],
       [79, 68, 66]], dtype=int32)

In [133]:
new = np.random.randint(1, 100, 144).reshape((12, 12)) 


In [134]:
print(new) 

[[51 53  7 67  2  2 34 61 12  7 82 57]
 [54 91 97 81 28 42 37 61 94 34 42 35]
 [26 86 35  8 18 65 49 71 27 52 65  4]
 [57 46 22 13 40 44 38 18 84 56 75 12]
 [66 98 91 40 31 26 61 11 99 65 12 48]
 [24 61 47 24 50 47 69 65  2 31 39 87]
 [60 26 14 54 23 49 59 38 44 85 47 22]
 [68 78 78 56 85 22 39 30  3 53 26 34]
 [17 25 78 81 51 47 36 67 26 65 49 36]
 [57 74  4  6 34 34 31 87 82 24 93 74]
 [90 84 30 55 37  3 71 37 23  9  4 81]
 [97 10 66 67 24 29 13 96 90 41 73 44]]


In [137]:
np.hsplit(new, 2) 

[array([[51, 53,  7, 67,  2,  2],
        [54, 91, 97, 81, 28, 42],
        [26, 86, 35,  8, 18, 65],
        [57, 46, 22, 13, 40, 44],
        [66, 98, 91, 40, 31, 26],
        [24, 61, 47, 24, 50, 47],
        [60, 26, 14, 54, 23, 49],
        [68, 78, 78, 56, 85, 22],
        [17, 25, 78, 81, 51, 47],
        [57, 74,  4,  6, 34, 34],
        [90, 84, 30, 55, 37,  3],
        [97, 10, 66, 67, 24, 29]], dtype=int32),
 array([[34, 61, 12,  7, 82, 57],
        [37, 61, 94, 34, 42, 35],
        [49, 71, 27, 52, 65,  4],
        [38, 18, 84, 56, 75, 12],
        [61, 11, 99, 65, 12, 48],
        [69, 65,  2, 31, 39, 87],
        [59, 38, 44, 85, 47, 22],
        [39, 30,  3, 53, 26, 34],
        [36, 67, 26, 65, 49, 36],
        [31, 87, 82, 24, 93, 74],
        [71, 37, 23,  9,  4, 81],
        [13, 96, 90, 41, 73, 44]], dtype=int32)]

In [138]:
np.vsplit(new, 4) 

[array([[51, 53,  7, 67,  2,  2, 34, 61, 12,  7, 82, 57],
        [54, 91, 97, 81, 28, 42, 37, 61, 94, 34, 42, 35],
        [26, 86, 35,  8, 18, 65, 49, 71, 27, 52, 65,  4]], dtype=int32),
 array([[57, 46, 22, 13, 40, 44, 38, 18, 84, 56, 75, 12],
        [66, 98, 91, 40, 31, 26, 61, 11, 99, 65, 12, 48],
        [24, 61, 47, 24, 50, 47, 69, 65,  2, 31, 39, 87]], dtype=int32),
 array([[60, 26, 14, 54, 23, 49, 59, 38, 44, 85, 47, 22],
        [68, 78, 78, 56, 85, 22, 39, 30,  3, 53, 26, 34],
        [17, 25, 78, 81, 51, 47, 36, 67, 26, 65, 49, 36]], dtype=int32),
 array([[57, 74,  4,  6, 34, 34, 31, 87, 82, 24, 93, 74],
        [90, 84, 30, 55, 37,  3, 71, 37, 23,  9,  4, 81],
        [97, 10, 66, 67, 24, 29, 13, 96, 90, 41, 73, 44]], dtype=int32)]

In [139]:
import pandas as pd 

In [141]:
pd.Series([1, 2 , 3, 4, 5], index = ['a', 'b', 'c', 'd', 'e']) 

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [142]:
# DataFrame 

In [143]:
d = {
    "Country" : ['India', 'Usa', 'Germany', 'Russia'],
    "Capital" : ['New Delhi', 'Washington D.C.', 'Berlin', 'Moscow'], 
    'Currency' : ['INR', 'USD', 'EUR', 'Ruble'], 
    'Development Status' : ['Developing', 'Developed', 'Developed', 'Developed']
}

In [145]:
df = pd.DataFrame(d) 

In [146]:
df

Country          Capital Currency Development Status
0    India        New Delhi      INR         Developing
1      Usa  Washington D.C.      USD          Developed
2  Germany           Berlin      EUR          Developed
3   Russia           Moscow    Ruble          Developed