In [1]:
import numpy as np 

In [2]:
'''
Creating of Numpy array 

np.array([list])
'''

'\nCreating of Numpy array \n\nnp.array([list])\n'

In [3]:
a = np.array([1, 2, 3, 4, 5]) 
b = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])

In [4]:
print(a) 

[1 2 3 4 5]


In [5]:
print(b) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# Initial PlaceHolders 

c = np.zeros((3,3)) 
print(c) 

d = np.ones((2, 5))
print(d) 

e = np.full((3, 2), 0) 
print(e) 

f = np.empty((3, 1)) 
print(f) 

g = np.eye(5) 
print(g) 

h = np.arange(20) 
print(h) 

i = np.linspace(1, 2, 5)
print(i) 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0 0]
 [0 0]
 [0 0]]
[[9.48479294e-312]
 [0.00000000e+000]
 [4.94065646e-324]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1.   1.25 1.5  1.75 2.  ]


In [7]:
import random

In [14]:
np.random.randint(10, 20, 5) 

NameError: name 'np' is not defined

In [9]:
np.random.random(10) 

array([0.90937744, 0.81061388, 0.58138715, 0.05384546, 0.19916652,
       0.93578819, 0.16338477, 0.96627187, 0.77449764, 0.42668285])

In [10]:
ord('9')

57

In [11]:
chr(122)

'z'

In [12]:
arr = np.arange(12).reshape((3,4)) 

In [13]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
# Inspect The Array 

print(f"Shape of array : {arr.shape} : Rows = {arr.shape[0]}, Columns : {arr.shape[1]}")
print(f"Size of array : {arr.size}")
print(f"Dimension of array : {arr.ndim}")
print(f"Length of array : {len(arr)}")
print(f"Data  Type of array Element : {type(arr)}")
print(f"The First Item : {arr[0][0]}, Its Data Type : {type(arr[0][0])}")
arr = arr.astype(np.float64)
print(arr) 

Shape of array : (3, 4) : Rows = 3, Columns : 4
Size of array : 12
Dimension of array : 2
Length of array : 3
Data  Type of array Element : <class 'numpy.ndarray'>
The First Item : 0, Its Data Type : <class 'numpy.int64'>
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [15]:
# Help function 

np.info(arr) 

class:  ndarray
shape:  (3, 4)
strides:  (32, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x1bef9ad5160
byteorder:  little
byteswap:  False
type: float64


In [16]:
# MatheMatical Operations 

a = [[1, 2], [3, 4]]
b = [[5, 6], [7, 8]] 

print(a, b) 

[[1, 2], [3, 4]] [[5, 6], [7, 8]]


In [17]:
# Arithematic Operators 

c = np.add(a, b)
print(c) 

[[ 6  8]
 [10 12]]


In [18]:
d = np.subtract(b, a) 
print(d) 

[[4 4]
 [4 4]]


In [19]:
e = np.multiply(a, b)
print(e) 

[[ 5 12]
 [21 32]]


In [20]:
f = np.divide(b, a) 
print(f)

[[5.         3.        ]
 [2.33333333 2.        ]]


In [21]:
np.exp(a) 

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [22]:
np.log(a) 

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [23]:
np.log10(a) 

array([[0.        , 0.30103   ],
       [0.47712125, 0.60205999]])

In [24]:
np.log2(a) 

array([[0.       , 1.       ],
       [1.5849625, 2.       ]])

In [25]:
np.sin(a) 

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [26]:
np.cos(a) 

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [27]:
np.tan(a) 

array([[ 1.55740772, -2.18503986],
       [-0.14254654,  1.15782128]])

In [28]:
np.dot(a, b) 

array([[19, 22],
       [43, 50]])

In [29]:
# Comparison 
print(a) 
print(b) 

[[1, 2], [3, 4]]
[[5, 6], [7, 8]]


In [30]:
np.equal(a, b) 

array([[False, False],
       [False, False]])

In [31]:
np.less(a, b) 

array([[ True,  True],
       [ True,  True]])

In [32]:
np.greater(a, b) 

array([[False, False],
       [False, False]])

In [33]:
np.less_equal(a, b) 

array([[ True,  True],
       [ True,  True]])

In [34]:
np.greater_equal(a, b) 

array([[False, False],
       [False, False]])

In [35]:
np.not_equal(a, b) 

array([[ True,  True],
       [ True,  True]])

In [36]:
arr = np.random.randint(1, 100, 10).reshape(2, 5) 

In [37]:
# Aggreate Functions 

# arr = np.array([int(item) for item in np.random.randint(1, 100, 10)])


print(f"main array \n{arr}") 

print(f"Minimum Element from whole array : {np.min(arr)}")
print(f"Column  Wise Smallest Element : {np.min(arr, axis = 0)}")
print(f"Row Wize Smallest Element : {np.min(arr, axis = 1)}")

print(f"\nmaximum Element from whole array : {np.max(arr)}")
print(f"Column  Wise Biggest Element : {np.max(arr, axis = 0)}")
print(f"Row Wize Biggest Element : {np.max(arr, axis = 1)}")


print(np.sum(arr, axis = 1)) 
print(np.average(arr, axis = 1))
print(np.std(arr)) 

main array 
[[29 45 24 16 42]
 [68 99  7 35  1]]
Minimum Element from whole array : 1
Column  Wise Smallest Element : [29 45  7 16  1]
Row Wize Smallest Element : [16  1]

maximum Element from whole array : 99
Column  Wise Biggest Element : [68 99 24 35 42]
Row Wize Biggest Element : [45 99]
[156 210]
[31.2 42. ]
27.86826151736057


In [39]:
# Creating a copy 

print(a) 

[[1, 2], [3, 4]]


In [46]:
c1 = a.copy() 
print(c1) 
c2 = np.copy(a) 
print(c2) 


[[1, 2], [3, 4]]
[[1 2]
 [3 4]]


In [68]:
a = np.random.randint(1, 100,10) 

In [69]:
print(a) 

[34  8 54 63 54 15 70 61 49 57]


In [70]:
a.sort(axis = 0, kind = 'quicksort') 

In [71]:
print(a) 

[ 8 15 34 49 54 54 57 61 63 70]


In [72]:
# a = a[::-1]

In [73]:
print(a) 

[ 8 15 34 49 54 54 57 61 63 70]


In [74]:
a = np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(a) 

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [76]:
# changing the shape to 1d 

one_d_data = a.ravel() 
print(one_d_data)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [77]:
new_shape = a.reshape((3,6)) 
print(new_shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [78]:
a.reshape((2, 3, 3))

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [80]:
final = a.reshape((3, 2, 3))

In [84]:
print(final)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [90]:
# Subsetting 

final[1][1][1]

np.int64(11)

In [96]:
final[:, 1: ,:2]

array([[[ 4,  5]],

       [[10, 11]],

       [[16, 17]]])

In [97]:
final[:, 0, 1:]

array([[ 2,  3],
       [ 8,  9],
       [14, 15]])

In [99]:
final

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [103]:
final[[0,0,0,1,1,1,2,2,2],[0,0,1,0,0,1,0,0,1],[0,2,1,0,2,1,0,2,1]]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [106]:
final[final % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [107]:
a = np.random.randint(1,100,9).reshape((3,3)) 

In [108]:
print(a) 

[[13 63  2]
 [35 88 42]
 [72 72 21]]


In [109]:
transpose_a = a.T
print(transpose_a)

[[13 35 72]
 [63 88 72]
 [ 2 42 21]]


In [111]:
a = np.random.randint(1, 100,9).reshape((3,3)) 
b = np.random.randint(1, 100,9).reshape((3,3)) 

In [112]:
print(a) 
print(b) 

[[36 65 15]
 [57 81 17]
 [92 93 57]]
[[18 25 93]
 [10  9 92]
 [57 50 75]]


In [116]:
np.concatenate((a, b), axis = 0) 

array([[36, 65, 15],
       [57, 81, 17],
       [92, 93, 57],
       [18, 25, 93],
       [10,  9, 92],
       [57, 50, 75]], dtype=int32)

In [120]:
np.c_[a, b]

array([[36, 65, 15, 18, 25, 93],
       [57, 81, 17, 10,  9, 92],
       [92, 93, 57, 57, 50, 75]], dtype=int32)

In [117]:
np.concatenate((a, b), axis = 1) 

array([[36, 65, 15, 18, 25, 93],
       [57, 81, 17, 10,  9, 92],
       [92, 93, 57, 57, 50, 75]], dtype=int32)

In [118]:
np.r_[a, b] 

array([[36, 65, 15],
       [57, 81, 17],
       [92, 93, 57],
       [18, 25, 93],
       [10,  9, 92],
       [57, 50, 75]], dtype=int32)

In [122]:
# Splitting array 

a = np.random.randint(1, 100, 36).reshape((6,6))


In [123]:
print(a) 

[[55 97 93 71 56 58]
 [79 92 93 86 70 14]
 [92 18  3 89 96 91]
 [47 61 80 93 29 11]
 [62 39 31 98 34 65]
 [56 99  7  9 91 52]]


In [128]:
np.hsplit(a, indices_or_sections=6) 

[array([[55],
        [79],
        [92],
        [47],
        [62],
        [56]], dtype=int32),
 array([[97],
        [92],
        [18],
        [61],
        [39],
        [99]], dtype=int32),
 array([[93],
        [93],
        [ 3],
        [80],
        [31],
        [ 7]], dtype=int32),
 array([[71],
        [86],
        [89],
        [93],
        [98],
        [ 9]], dtype=int32),
 array([[56],
        [70],
        [96],
        [29],
        [34],
        [91]], dtype=int32),
 array([[58],
        [14],
        [91],
        [11],
        [65],
        [52]], dtype=int32)]

In [129]:
np.vsplit(a, 6) 

[array([[55, 97, 93, 71, 56, 58]], dtype=int32),
 array([[79, 92, 93, 86, 70, 14]], dtype=int32),
 array([[92, 18,  3, 89, 96, 91]], dtype=int32),
 array([[47, 61, 80, 93, 29, 11]], dtype=int32),
 array([[62, 39, 31, 98, 34, 65]], dtype=int32),
 array([[56, 99,  7,  9, 91, 52]], dtype=int32)]